public enum Identifiers 
{
    NULL,
    EMPTY_PLATFORM,
    PLACEHOLDER_PLATFORM,
    STONE_PLATFORM,
    SOIL_PLATFORM,
    DIG_SITE_PLATFORM,

    TREE_BUILDING,
    LIGHTSOURCE_BUILDING,
    CONDENSER_BUILDING,    
    GENERATOR_BUILDING,    
    TURBINE_BUILDING,    
    MINERAL_HARVESTER_BUILDING,
    MINERAL_MINER_BUILDING,    
    OIL_PUMP_BUILDING,    
    WATER_WELL_BUILDING
}

public enum ResourceIdentifiers
{
    WATER,
    ENERGY,
    LIGHT,
    COOL,
    OIL,
    MINERALS
}
