public enum Identifiers : int
{
    NULL = 0,
    EMPTY_PLATFORM = 1,
    PLACEHOLDER_PLATFORM = 2,
    STONE_PLATFORM = 3,
    SOIL_PLATFORM = 4,
    DIG_SITE_PLATFORM = 5,

    TREE_BUILDING = 6,
    LIGHTSOURCE_BUILDING = 7,
    CONDENSER_BUILDING = 8,    
    GENERATOR_BUILDING = 9,    
    TURBINE_BUILDING = 10,    
    MINERAL_HARVESTER_BUILDING = 11,
    MINERAL_MINER_BUILDING = 12,    
    OIL_PUMP_BUILDING = 13,    
    WATER_WELL_BUILDING = 14,
    SOLAR_PANEL_BUILDING = 15
}

public enum ResourceIdentifiers
{
    NULL = 0,
    WATER = 1,
    ENERGY = 2,
    LIGHT = 3,
    COOL = 4,
    OIL = 5,
    MINERALS = 6
}
