public enum Identifiers 
{
    NULL,
    EMPTY_PLATFORM,
    PLACEHOLDER_PLATFORM,
    STONE_PLATFORM,
    MINING_PLATFORM,
    SOIL_PLATFORM,
    TREE_BUILDING,
    LIGHTSOURCE_BUILDING,
    CONDENSER_BUILDING,    
    GENERATOR_BUILDING,    
    TURBINE_BUILDING,    
}

public enum ResourceIdentifiers
{
    WATER,
    ENERGY,
    LIGHT
}
